spring:
  application:
    name: manager

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

class:
  code:
    - "5413"
    - "5414"
    - "5527"
    - "5507"
    - "5508"
    - "627-A"
    - "627-B"