spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

admin:
  super:
    id: ${ADMIN_ID}
    password: ${ADMIN_PASSWORD}
    name: ${ADMIN_NAME}
    contact: ${ADMIN_CONTACT}

jwt:
  access-token-expiration-day: ${JWT_EXPIRATION_DAYS}
  secret-key: ${JWT_SECRET_KEY}

front:
  url: ${FRONTEND_URL}

logging:
  level:
    root: INFO
    com.yourpackage: INFO